version: '3.8'

services:

  db:
    image: postgres:15.0-alpine3.16
    container_name: hashtag-db
    volumes:
      - postgres_db:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_DB=hashtags

  backend:
    build: . # use Dockerfile that exists on same directory as docker-compose.yml
    container_name: hashtag-backend
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=hashtags
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: hashtag-pgadmin
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin-password

volumes:
  postgres_db:
